# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JRpersonal.STReborn
PackageVersion: 1.0.2
InstallerType: portable
Commands:
- streborn
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JRpersonal/streborn/releases/download/v1.0.2/STR-Windows.exe
  InstallerSha256: D44E24B804E99B08C37DA739D34854F1D6EF0811BF656B29F44067105FE40A86
ManifestType: installer
ManifestVersion: 1.12.0
